#Images equipements AgriCore
#Sat Feb 28 22:47:39 WAT 2026
fea=C\:\\Users\\SBS\\Desktop\\WORKOUT\\PROJET JAVA\\Projet-JAVA\\images_equipements\\fea.jpg
feaef=C\:\\Users\\SBS\\Desktop\\WORKOUT\\PROJET JAVA\\Projet-JAVA\\images_equipements\\feaef.jpg
